# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ledger.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cledger.proto\"6\n\x12\x45xpenseTransaction\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x62\x06proto3'
)




_EXPENSETRANSACTION = _descriptor.Descriptor(
  name='ExpenseTransaction',
  full_name='ExpenseTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category', full_name='ExpenseTransaction.category', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='ExpenseTransaction.amount', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['ExpenseTransaction'] = _EXPENSETRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExpenseTransaction = _reflection.GeneratedProtocolMessageType('ExpenseTransaction', (_message.Message,), {
  'DESCRIPTOR' : _EXPENSETRANSACTION,
  '__module__' : 'ledger_pb2'
  # @@protoc_insertion_point(class_scope:ExpenseTransaction)
  })
_sym_db.RegisterMessage(ExpenseTransaction)


# @@protoc_insertion_point(module_scope)
